name: Main
on:
  push:
    branches:
      - master
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK 17'
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: 'maven'
      - name: 'Build'
        shell: bash
        run: mvn -V --no-transfer-progress clean verify --fail-at-end
